env_common: add missing trustfence.h include
The trustfence.h header was not being included, which causes the following warning:

common/env_common.c: In function ‘env_aes_cbc_crypt’:
common/env_common.c:174:8: warning: implicit declaration of function ‘get_trustfence_key_modifier’ [-Wimplicit-function-declaration]
  ret = get_trustfence_key_modifier(key_modifier);

More importantly, it also broke the U-Boot environment decryption support.

https://jira.digi.com/browse/DEL-6224

Signed-off-by: Jose Diaz de Grenu <Jose.DiazdeGrenu@digi.com>
(cherry picked from commit 96bce8e1805206eb5982438ba4b514881ddacd55)