image-android: remove header that produced nested redefinition
In file included from common/image-android.c:20:
./arch/arm/include/asm/mach-imx/boot_mode.h:13:6: error: nested redefinition of 'enum boot_device'
   13 | enum boot_device {
      |      ^~~~~~~~~~~
./arch/arm/include/asm/mach-imx/boot_mode.h:13:6: error: redeclaration of 'enum boot_device'
In file included from include/configs/stm32mp1.h:11,
                 from include/config.h:4,
                 from include/common.h:16,
                 from common/image-android.c:9:
./arch/arm/include/asm/arch/stm32.h:58:6: note: originally defined here
   58 | enum boot_device {
      |      ^~~~~~~~~~~

The header is not required to build Digi IMX platforms anyway.

Signed-off-by: Hector Palacios <hector.palacios@digi.com>