MLK-22830 mx7ulp: Fix build break of mx7ulp_evk_m4boot_defconfig
Get build error when using mx7ulp_evk_m4boot_defconfig

  arch/arm/lib/built-in.o: In function `setup_serial_tag':
  /home/leyoen/Workspace/uboot-imx/arch/arm/lib/bootm.c:191:
  undefined reference to `get_board_serial'

The boot cause is CONFIG_SERIAL_TAG is defined in header file
without depending on fastboot, but the function definition uses
CONFIG_FSL_FASTBOOT. So remove the wrong macro from function
definition to fix the issue

Signed-off-by: Ye Li <ye.li@nxp.com>
Reviewed-by: Peng Fan <peng.fan@nxp.com>