ccimx6sbc: add missing trustfence.h include
The trustfence.h header was not being included, which causes the following warning:

board/digi/ccimx6sbc/ccimx6sbc.c: In function ‘board_early_init_f’:
board/digi/ccimx6sbc/ccimx6sbc.c:384:6: warning: implicit declaration of function ‘console_enable_gpio’; did you mean ‘config_enabled’? [-Wimplicit-function-declaration]
  if (console_enable_gpio(console_enable_gpio_nr))
      ^~~~~~~~~~~~~~~~~~~

While at it, also fix it for ccimx6ulsbc and ccimx6ulstarter.

Signed-off-by: Gonzalo Ruiz <Gonzalo.Ruiz@digi.com>