hab.h: add missing include
Fixes:

./arch/arm/include/asm/mach-imx/hab.h:190:24: warning: implicit declaration of function ‘is_mx6dqp’ [-Wimplicit-function-declaration]
 #define HAB_RVT_BASE ((is_mx6dqp()) ?     \
                        ^

Signed-off-by: Jose Diaz de Grenu <Jose.DiazdeGrenu@digi.com>