ccimx8x-sbc-pro: add missing functions needed for android
Otherwise a build configuration enabling Android needed functionality
fails with:

image-android.c:101: undefined reference to `mmc_map_to_kernel_blk'
fb_fsl_command.c:95: undefined reference to `is_recovery_key_pressing'

https://jira.digi.com/browse/ADK4A-1792

Signed-off-by: Javier Viguera <javier.viguera@digi.com>