ccimx8x_sbc_pro: add missing environment vars for Android
For example, running "dboot android mmc" fails with:

Error: "bootargs_mmc_android" not defined

https://jira.digi.com/browse/DUB-878

Signed-off-by: Javier Viguera <javier.viguera@digi.com>
(cherry picked from commit f8b7b3a80a15da204a67524176d167770e83929e)